apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
name: openshift-user-workload-og
namespace: openshift-user-workload-monitoring
spec:
  targetNamespaces:
  - openshift-user-workload-monitoring

