{
 "title": "Example Metrics - Golden Signals",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(greeting_seconds_count{}[2m]))"
    }
   ]
  },
  {
   "title": "Errors Per Second",
   "type": "graph",
   "gridPos": { "h": 15, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(greeting_seconds_count{code!=\"200\"}[2m]))"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "description": "// Average Latency",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(greeting_seconds_sum)/sum(greeting_seconds_count)"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(greeting_seconds_bucket[5m])) by (le))"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate{namespace='example-metrics'}) by (pod)"
    }
   ]
  }
 ]
}