apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: example-metrics-dashboard
  namespace: openshift-user-workload-monitoring
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  config: {}
  ingress:
    enabled: true
