apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PostSync
  name: grafana-post-sync-job
spec:
  template:
    spec:
      containers:
        - image: registry.redhat.io/openshift4/ose-cli:v4.9
          command:
            - /bin/bash
            - -c
            - |
              BEARER_TOKEN=$(oc serviceaccounts get-token grafana-serviceaccount -n openshift-user-workload-monitoring 2>&1)
              THANOS_URL=$(oc get route thanos-querier -n openshift-monitoring --template={{.spec.host}} 2>&1)
              
              oc adm policy add-cluster-role-to-user cluster-monitoring-view -z grafana-serviceaccount
              
              cat <<EOF | oc apply -f -
              apiVersion: integreatly.org/v1alpha1
              kind: GrafanaDataSource
              metadata:
                name: example-metrics-datasource
                namespace: openshift-user-workload-monitoring
              spec:
                datasources:
                  - access: proxy
                    editable: true
                    isDefault: true
                    jsonData:
                      httpHeaderName1: 'Authorization'
                      timeInterval: 5s
                      tlsSkipVerify: true
                    name: Prometheus
                    secureJsonData:
                      httpHeaderValue1: 'Bearer ${BEARER_TOKEN}'
                    type: prometheus
                    url: https://${THANOS_URL}
                name: example-metrics-datasource.yaml
              EOF
          imagePullPolicy: Always
          name: grafana-datasource-apply-script
      dnsPolicy: ClusterFirst
      restartPolicy: OnFailure
      serviceAccountName: grafana-post-sync-sa
      terminationGracePeriodSeconds: 90
