apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: example-metrics-dashboard
  namespace: openshift-user-workload-monitoring
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/sync-wave: "1"
spec:
  config: {}
  ingress:
    enabled: true
