apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  name: grafana-post-sync-rbac
rules:
  - verbs:
      - '*'
    apiGroups:
      - integreatly.org
      - rbac.authorization.k8s.io
      - '*'
    resources:
      - grafanadatasources
      - clusterrolebindings
      - namespaces
      - '*'
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-post-sync-rolebinding
  annotations:
    argocd.argoproj.io/sync-wave: "0"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: grafana-post-sync-rbac
subjects:
  - kind: ServiceAccount
    name: grafana-post-sync-sa
    namespace: openshift-user-workload-monitoring
