apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources: 
- grafana-sub.yaml
- grafana-operator-group.yaml
- grafana-instance.yaml
- grafana-dashboard-instance.yaml
- grafana-post-sync-rbac.yaml
- grafana-post-sync-sa.yaml
