apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: maistraoperator
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: maistraoperator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: maistraoperator.v2.1.0
