apiVersion: integreatly.org/v1alpha1
kind: Grafana
metadata:
  name: example-metrics-grafana-instance
  namespace: openshift-user-workload-monitoring
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  dashboardLabelSelector:
    - matchLabels:
        app: example-metrics
  config: {}
  ingress:
    enabled: true
